# Generated by Django 4.0.5 on 2022-07-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nameofstocks', models.CharField(max_length=30)),
                ('buy', models.IntegerField()),
                ('buydate', models.DateField(blank=True, null=True)),
                ('sell', models.IntegerField()),
                ('selldate', models.DateField(blank=True, null=True)),
                ('t1', models.IntegerField(blank=True, null=True)),
                ('t2', models.IntegerField(blank=True, null=True)),
                ('profit', models.BooleanField(blank=True, null=True)),
                ('loss', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
