# Generated by Django 4.0.5 on 2022-07-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
